### ISSUE TITLE
Forms Components

### ISSUE THREAD

**Issue by zilva149** [front-end-by-rimantas/40-grupe-portfolio-braintech#35]
- [x] write structure in html-templates.html under relevant comment
- [x] write style in forms.css
- [x] appointment form `class="appointment-form"`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- heading `h4`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- `p` description text
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- text input `<input type="text">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- email input `<input type="email">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- tel input `<input type="tel">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- url input `<input type="url">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- submit input `input type="submit"`
- [x] box-shadow (`var(--default-shadow)`)
![image](https://user-images.githubusercontent.com/114074935/199963604-54448719-60a6-4621-9bdd-84daea3bd86c.png)

- [ ] footer form `class="newsletter-form"`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-  email input `<input type="email">`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- submit input `<input type="submit">`
![image](https://user-images.githubusercontent.com/114074935/199963803-7f48c0da-bb38-4551-b6e5-9ee9d0cc57e0.png)

**Comment by ayobamiseun** [comment]
I will like to work on this.

**Comment by zilva149** [comment]
> I will like to work on this.

Hello, our team is already formed. Maybe you are from a different team :).
