### ISSUE TITLE
Socials Components

### ISSUE THREAD

**Issue by zilva149** [front-end-by-rimantas/40-grupe-portfolio-braintech#36]
- [x] write structure in html-templates.html under relevant comment
- [x] write style in socials.css
- [x] footer socials `class="footer-socials"`
![image](https://user-images.githubusercontent.com/114074935/199965982-13910770-1f13-4ab5-8f2e-6026fcd61471.png)

- [x] header socials  `class="header-socials"`
![image](https://user-images.githubusercontent.com/114074935/199966209-b3c5bea7-27bb-4c80-b574-93f6644592b3.png)

- [x] sidebar socials  `class="sidebar-socials"`
![image](https://user-images.githubusercontent.com/114074935/199966119-c04891c8-7c6c-4479-94d0-5362bb1da459.png)

**Comment by ayobamiseun** [comment]
can I work on this?
